"""LegalEase - AI-powered legal document generator (BCA final year project)."""
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs
from html import escape
import sqlite3, os, io, json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm

BASE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE, 'instance', 'legalease.db')
os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)

TEMPLATES = {
    'Rental Agreement': ['client_name','other_party','property','start_date','end_date','rent','jurisdiction'],
    'Employment Contract': ['client_name','other_party','position','start_date','salary','location','jurisdiction'],
    'Non-Disclosure Agreement': ['client_name','other_party','purpose','duration','jurisdiction'],
    'Affidavit': ['client_name','address','purpose','date','jurisdiction']
}
LABELS = {
    'client_name':'Tenant / Client Name','other_party':'Other Party Name','property':'Property Address','start_date':'Start Date','end_date':'End Date','rent':'Monthly Rent','position':'Job Title','salary':'Annual Salary','location':'Work Location','purpose':'Purpose / Statement','duration':'Confidentiality Period','address':'Address','date':'Declaration Date','jurisdiction':'Jurisdiction'
}

def db():
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    return con

def init_db():
    with db() as con:
        con.execute('''CREATE TABLE IF NOT EXISTS legal_documents (
            id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, document_type TEXT NOT NULL,
            client_name TEXT NOT NULL, jurisdiction TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL)''')

def val(data, key, default=''):
    return (data.get(key, [default]) or [default])[0].strip()

def generate_document(doc_type, data):
    client=val(data,'client_name','the Client'); other=val(data,'other_party','the Other Party'); jurisdiction=val(data,'jurisdiction','the applicable jurisdiction')
    common=f"{doc_type.upper()}\n\nGenerated by LegalEase for academic drafting purposes. This is not legal advice and should be reviewed by a qualified legal professional.\n\nJURISDICTION: {jurisdiction}\n\n"
    if doc_type=='Rental Agreement':
        body=f"1. PARTIES\nThis Rental Agreement is entered into between {client} (Tenant) and {other} (Landlord).\n\n2. PREMISES\nThe premises are located at {val(data,'property','[Property Address]')}.\n\n3. TERM\nThe tenancy begins on {val(data,'start_date','[Start Date]')} and ends on {val(data,'end_date','[End Date]')}.\n\n4. RENT\nThe Tenant shall pay a monthly rent of {val(data,'rent','[Monthly Rent]')}, subject to the agreed terms.\n\n5. RESPONSIBILITIES\nThe parties shall comply with applicable law and agreed maintenance and usage obligations.\n\n6. TERMINATION\nTermination shall follow applicable law and any notice requirements."
    elif doc_type=='Employment Contract':
        body=f"1. PARTIES\nThis Employment Contract is between {other} (Employer) and {client} (Employee).\n\n2. POSITION\nThe Employee will serve as {val(data,'position','[Job Title]')}.\n\n3. COMMENCEMENT\nEmployment begins on {val(data,'start_date','[Start Date]')}.\n\n4. COMPENSATION\nThe annual salary is {val(data,'salary','[Annual Salary]')}, subject to applicable deductions.\n\n5. WORK LOCATION\nThe normal work location is {val(data,'location','[Work Location]')}.\n\n6. CONFIDENTIALITY\nThe Employee shall protect confidential business information.\n\n7. TERMINATION\nTermination will be handled in accordance with applicable employment law and this agreement."
    elif doc_type=='Non-Disclosure Agreement':
        body=f"1. PARTIES\nThe Disclosing Party is {other}. The Receiving Party is {client}.\n\n2. PURPOSE\nConfidential information may be shared for: {val(data,'purpose','[Purpose]')}.\n\n3. CONFIDENTIAL INFORMATION\nConfidential information includes non-public business, technical, financial, customer, or other information identified as confidential or reasonably understood to be confidential.\n\n4. USE AND DISCLOSURE\nThe Receiving Party shall use confidential information only for the stated purpose and shall not disclose it except as permitted by law or with written authorization.\n\n5. DURATION\nConfidentiality obligations apply for {val(data,'duration','[Confidentiality Period]')}.\n\n6. GOVERNING LAW\nThis agreement shall be interpreted with reference to the laws applicable in {jurisdiction}."
    else:
        body=f"I, {client}, residing at {val(data,'address','[Address]')}, solemnly declare the following:\n\n1. PURPOSE\n{val(data,'purpose','[Purpose / Statement]')}\n\n2. DECLARATION\nThe statements made in this affidavit are declared to be true and correct to the best of my knowledge and belief.\n\n3. DATE\nThis declaration is made on {val(data,'date','[Declaration Date]')}.\n\n4. JURISDICTION\nThis affidavit is intended for use in {jurisdiction}.\n\nDECLARANT\nName: {client}\nSignature: __________________________\nDate: ______________________________"
    return common+body+"\n\nSIGNATURES\n\nClient / First Party: __________________________\n\nOther Party: _________________________________\n\nDate: _______________________________________"

def page(title, content):
    css=open(os.path.join(BASE,'static','style.css'),encoding='utf8').read()
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LegalEase</title><style>{css}</style></head><body><nav><a class="brand" href="/">⚖ LegalEase</a><div><a href="/">Dashboard</a><a href="/generate">Generate Document</a></div></nav><main>{content}</main><footer>LegalEase • AI-powered legal document drafting prototype • Educational use</footer></body></html>'''

def home():
    with db() as con: docs=con.execute('SELECT * FROM legal_documents ORDER BY id DESC LIMIT 5').fetchall(); count=con.execute('SELECT COUNT(*) FROM legal_documents').fetchone()[0]
    cards=''.join(f'<a class="doc-card" href="/document/{r["id"]}"><span class="icon">▤</span><div><b>{escape(r["document_type"])}</b><p>{escape(r["client_name"])} · {escape(r["jurisdiction"])}</p><small>{escape(r["created_at"])}</small></div></a>' for r in docs) or '<div class="empty">No documents yet. Create your first legal draft.</div>'
    content=f'''<section class="hero"><div><p class="eyebrow">BCA FINAL YEAR PROJECT</p><h1>Legal documents,<br><span>simplified.</span></h1><p>Generate structured legal-document drafts from simple form inputs, save them in SQLite, and export polished PDFs.</p><a class="btn" href="/generate">Create a document →</a></div><div class="hero-card"><div class="scale">⚖</div><b>LegalEase AI</b><small>Smart drafting assistant</small><div class="mini-line"></div><div class="mini-row"><span>Documents generated</span><strong>{count}</strong></div></div></section><section class="section"><div class="section-head"><div><p class="eyebrow">RECENT</p><h2>Document workspace</h2></div><a href="/generate">+ New document</a></div><div class="cards">{cards}</div></section>'''
    return page('LegalEase',content)

def form_page(doc_type='Rental Agreement', error=''):
    fields=TEMPLATES[doc_type]
    options=''.join(f'<option value="{escape(t)}" {"selected" if t==doc_type else ""}>{escape(t)}</option>' for t in TEMPLATES)
    inputs=''.join(f'<label>{escape(LABELS[f])}<input name="{f}" placeholder="Enter {escape(LABELS[f]).lower()}" required></label>' for f in fields)
    content=f'''<div class="page-head"><p class="eyebrow">DOCUMENT GENERATOR</p><h1>Create a legal draft</h1><p>Choose a document type and provide the facts. LegalEase creates a structured first draft.</p></div>{f'<div class="flash error">{escape(error)}</div>' if error else ''}<form class="form-card" method="post" action="/generate"><label>Document Type<select name="document_type" onchange="document.getElementById('typeForm').submit()">{options}</select></label><div class="grid">{inputs}</div><button class="btn" type="submit">Generate with LegalEase AI →</button><p class="hint">Academic prototype. Review generated text with a qualified legal professional before real-world use.</p></form>'''
    # JS form submits only type change through GET to avoid losing typed data; replace with simple link behavior.
    content=content.replace("onchange=\"document.getElementById('typeForm').submit()\"", "onchange=\"window.location='/generate?document_type='+encodeURIComponent(this.value)\"")
    return page('Generate',content)

def document_page(doc_id):
    with db() as con: r=con.execute('SELECT * FROM legal_documents WHERE id=?',(doc_id,)).fetchone()
    if not r: return page('Not found','<div class="empty">Document not found.</div>'),404
    blocks=''.join(f'<p>{escape(b).replace(chr(10),"<br>")}</p>' for b in r['content'].split('\n\n'))
    content=f'''<div class="doc-toolbar"><div><p class="eyebrow">GENERATED DOCUMENT #{r['id']}</p><h1>{escape(r['document_type'])}</h1><p>{escape(r['client_name'])} · {escape(r['jurisdiction'])}</p></div><div><a class="btn secondary" href="/generate">New</a> <a class="btn" href="/document/{r['id']}/download">Download PDF</a></div></div><article class="paper">{blocks}</article>'''
    return page('Document',content)

def pdf_bytes(row):
    stream=io.BytesIO(); pdf=SimpleDocTemplate(stream,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=18*mm,bottomMargin=18*mm)
    styles=getSampleStyleSheet(); styles['Title'].alignment=TA_CENTER
    story=[Paragraph(escape(row['document_type']),styles['Title']),Spacer(1,10)]
    for block in row['content'].split('\n\n'):
        story.append(Paragraph(escape(block).replace('\n','<br/>'),styles['BodyText'])); story.append(Spacer(1,7))
    pdf.build(story); return stream.getvalue()

class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt,*args): pass
    def send_html(self, body, status=200):
        data=body.encode('utf8'); self.send_response(status); self.send_header('Content-Type','text/html; charset=utf-8'); self.send_header('Content-Length',str(len(data))); self.end_headers(); self.wfile.write(data)
    def do_GET(self):
        u=urlparse(self.path); path=u.path; q=parse_qs(u.query)
        if path=='/': self.send_html(home()); return
        if path=='/generate':
            typ=val(q,'document_type','Rental Agreement'); self.send_html(form_page(typ if typ in TEMPLATES else 'Rental Agreement')); return
        m=__import__('re').match(r'^/document/(\d+)$',path)
        if m:
            body,status=document_page(int(m.group(1))); self.send_html(body,status); return
        m=__import__('re').match(r'^/document/(\d+)/download$',path)
        if m:
            with db() as con: row=con.execute('SELECT * FROM legal_documents WHERE id=?',(int(m.group(1)),)).fetchone()
            if not row: self.send_html('<h1>Not found</h1>',404); return
            data=pdf_bytes(row); self.send_response(200); self.send_header('Content-Type','application/pdf'); self.send_header('Content-Disposition',f'attachment; filename=LegalEase_Document_{row["id"]}.pdf'); self.send_header('Content-Length',str(len(data))); self.end_headers(); self.wfile.write(data); return
        self.send_html('<h1>404</h1>',404)
    def do_POST(self):
        u=urlparse(self.path)
        length=int(self.headers.get('Content-Length','0')); raw=self.rfile.read(length).decode('utf8')
        if u.path=='/generate':
            data=parse_qs(raw); typ=val(data,'document_type','Rental Agreement')
            if typ not in TEMPLATES: typ='Rental Agreement'
            content=generate_document(typ,data); client=val(data,'client_name','Draft Client'); jurisdiction=val(data,'jurisdiction','Not specified'); now=datetime.now().strftime('%d %b %Y, %I:%M %p')
            with db() as con:
                cur=con.execute('INSERT INTO legal_documents(title,document_type,client_name,jurisdiction,content,created_at) VALUES(?,?,?,?,?,?)',(f'{typ} - {client}',typ,client,jurisdiction,content,now)); doc_id=cur.lastrowid
            self.send_response(303); self.send_header('Location',f'/document/{doc_id}'); self.end_headers(); return
        if u.path=='/api/generate':
            try:
                data=json.loads(raw); typ=data.get('document_type','Rental Agreement'); content=generate_document(typ,{k:[str(v)] for k,v in data.items()}); out=json.dumps({'document_type':typ,'content':content}).encode(); self.send_response(200); self.send_header('Content-Type','application/json'); self.send_header('Content-Length',str(len(out))); self.end_headers(); self.wfile.write(out)
            except Exception as e: self.send_response(400); self.end_headers()
        else: self.send_html('<h1>404</h1>',404)

if __name__=='__main__':
    init_db(); server=ThreadingHTTPServer(('127.0.0.1',5000),Handler); print('LegalEase running at http://127.0.0.1:5000'); server.serve_forever()
